### ISSUE TITLE
targeting drop down field

### ISSUE THREAD

**Issue by liranmas** [jthorat10/Google_form_filler#1]
Hi there!
Thank you for the detailed and well-commented code!
I'm trying to target a drop-down field with no success in **choosing** one of the options within it. did you ever try something like that?
also, what would be the best way to support multi-stage form? just to target the "next" button and hit it with a timer?
Thx!
Liran

**Comment by jaythorat** [comment]
Hey, I'll look into it n let you know ASAP. Sorry  for the delay in reply.

**Comment by jaythorat** [comment]
Hey @liranmas,  You cannot access dropdown options because they are not keyboard-focusable.
So what I did is - 
1 - Maximize the window after passing the URL to the driver with  `driver.maximize_window()` 
2 - With the help of this line you'll be able to open options menu
    - If only one DROPDOWN is there in the form use `driver.find_element_by_xpath("//div[@role='option']").click()`
    - If more than one are there then use `driver.find_element_by_xpath("//div[@role='option']")[index of dropdown].click()` 
 
3 - Then `import pyautogui` and click on the desired option by using -
      `pyautogui.moveTo(798, 453)` 
       `pyautogui.leftClick(798,453)`
       Replace the co-ordinates of .moveTo & leftClick according to your need.
[https://chrome.google.com/webstore/detail/coordinates/bpflbjmbfccblbhlcmlgkajdpoiepmkd](CoOrdinates extension for chrome)
